aemsites/mmsg-oly

styles/styles.css

Test URLs:
- Before: https://main--mmsg-oly--aemsites.hlx.page/
- After: https://baseStyles--mmsg-oly--aemsites.hlx.page/

Base styles added

---

blocks/footer/footer.css
blocks/footer/footer.js

This PR contains the initial version of the footer component.
Things left to do:
- Update the footer social icons as per the figma
- update the logo image and footer image as per the images provided.
- Contact Oly button will be updated post changes in the typography files
Test URLs:
- After: https://footer--mmsg-oly--aemsites.hlx.live/

first version of the footer component

---

component-models.json

Test URLs:
- After: https://feature-hero-component--mmsg-oly--aemsites.hlx.live/

Updated component models json file for hero baner

---

styles/styles.css

Changes in this PR is for the notification bar.
Changes are made in the styles.css so that they are aligned with the LCP.
Also added a font and spacing as it is required for the other components as well
Test URLs:
- After: https://notification--mmsg-oly--aemsites.hlx.live/

Changes for the notification bar

---

blocks/hero/hero.css
blocks/hero/hero.js
component-definition.json
component-models.json
styles/styles.css

- Added two variation of hero component.
- Added dropdown to select variation from universal editor.
Test URLs:
- After: https://feature-hero-component--mmsg-oly--aemsites.hlx.live/

[feature/hero-component] Added variation of hero component

---

blocks/hero/hero.css
styles/styles.css

Test URLs:
- Before: https://main--mmsg-oly--aemsites.hlx.live/typography
- After: https://228041-button--mmsg-oly--aemsites.hlx.live/typography

Button CSS added for three variations

---

blocks/columns/columns.css

This PR contains the changes for the column component with 2 variation.
ToDo:
Buttons will be replaced with correct ones, once they are created in the typography
Test URLs:
- After: https://column-with-variation--mmsg-oly--aemsites.hlx.live/
**Screenshots
1. Variation1**
- Desktop
- Tablet
-Mobile
**2. Variation2**
- Desktop
Tablet
Mobile

initial commit for column component with 2 variations

---

component-definition.json
component-filters.json
component-models.json

This PR contains the component modeling, definition and filter changes for carousel component.
carousel contains slides, which are also modelled here.
UE Link - https://author-p136205-e1368144.adobeaemcloud.com/ui#/@mmsg/aem/universal-editor/canvas/author-p136205-e1368144.adobeaemcloud.com/content/oly/index.html/?ref=3-slide-carousel
Test URLs:
- After: https://3-slide-carousel--mmsg-oly--aemsites.hlx.live/

component modeling for 3 slide carousel

---

blocks/savingscard/savingscard.css
blocks/savingscard/savingscard.js
component-models.json

Test URLs:
- After: https://SavingsCard-Block--mmsg-oly--aemsites.hlx.live/

Updating the savings card block styles

---

blocks/savingscard/savingscard.css
blocks/savingscard/savingscard.js
component-definition.json
component-models.json

Test URLs:
- After: https://SavingsCard-Block--mmsg-oly--aemsites.hlx.live/

Updating model and styles for the savings card block

---

blocks/savingscard/savingscard.css

Test URLs:
- After: https://SavingsCard-Block--mmsg-oly--aemsites.hlx.live/

Savings card block - Styles updated

---

blocks/savingscard/savingscard.css
blocks/savingscard/savingscard.js
component-definition.json
component-models.json

Test URLs:
- After: https://SavingsCard-Block--mmsg-oly--aemsites.hlx.live/

Savings card block

---

blocks/savingscard/savingscard.css
blocks/savingscard/savingscard.js

Test URLs:
- After: https://savingscard-block--mmsg-oly--aemsites.hlx.live/

Updating DOM and styles for the savings card block

---

.eslintrc.js
blocks/footer/footer.css

This PR contains few changes WRT figma.
desktop ss - 
mobile ss-
tablet -
Test URLs:
- After: https://footer-changes--mmsg-oly--aemsites.hlx.live/

Footer changes wrt figma

---

blocks/savingscard/savingscard.css
styles/styles.css

Test URLs:
- After: https://SavingsCard-block--mmsg-oly--aemsites.hlx.live/

Updating the styles for the savings card block

---

paths.json

Test URLs:
- After: https://paths-json-change--mmsg-oly--aemsites.hlx.live/

project languages(au/en) paths json change

---

paths.json

Test URLs:
- After: https://path-updates--mmsg-oly--aemsites.hlx.live/

path json path updated

---

blocks/imagedesc-card-inline/imagedesc-card-inline.js
component-models.json

Test URLs:
- After: https://DidYouKnow-Block--mmsg-oly--aemsites.hlx.live/

Adding the initial version of imagedesc-card-horizontal block

---

blocks/imagedesc-card-inline/imagedesc-card-inline.css
component-models.json

Test URLs:
- After: https://DidyouKnow-block--mmsg-oly--aemsites.hlx.live/

Updating the imagedesc-card-horizontal block

---

paths.json

Test URLs:
- After: https://pathquery--mmsg-oly--aemsites.hlx.live/

indexing configuration added

---

paths.json

Test URLs:
- After: https://pathquery--mmsg-oly--aemsites.hlx.live/

path configuration udpated

---

blocks/savingscard/savingscard.js

Test URLs:
- After: https://savingscard-block--mmsg-oly--aemsites.hlx.live/

Updating the Savings card block

---

blocks/thumbnail_desc/thumbnail_desc.css
blocks/thumbnail_desc/thumbnail_desc.js
component-definition.json
component-filters.json
component-models.json
package-lock.json
package.json

Test URLs:
- After: https://thumbnailDesc--mmsg-oly--aemsites.hlx.live/

Thumbnail desc

---

blocks/thumbnail_desc/thumbnail_desc.css
blocks/thumbnail_desc/thumbnail_desc.js
component-definition.json
component-filters.json
component-models.json

Test URLs:
- After: https://thumbnail_desc_component--mmsg-oly--aemsites.hlx.live/

initial commit for thumbnail description component

---

component-definition.json
component-models.json

Test URLs:
- After: https://vehicleSearch--mmsg-oly--aemsites.hlx.live/

Creating a sample vehicle search box

---

blocks/columns/columns.css

Test URLs:
- After: https://whats-included--mmsg-oly--aemsites.hlx.live/

adding whats-included block of electric vehicle

---

component-definition.json
component-models.json

Test URLs:
- After: https://card-dynamic--mmsg-oly--aemsites.hlx.live/

Adding dropdown to the card component for the card Colors

---

component-definition.json
component-models.json

Test URLs:
- After: https://card-dynamic--mmsg-oly--aemsites.hlx.live/

Card dynamic

---

blocks/imagedesc-col3-inline/imagedesc-col3-inline.css
blocks/imagedesc-col3-inline/imagedesc-col3-inline.js
component-definition.json
component-filters.json
component-models.json

Test URLs:
- After: https://imagedesc-col3-inline--mmsg-oly--aemsites.hlx.live/

Adding the initial version of the imagedesc-col3-inline block

---

paths.json

Test URLs:
- After: https://mrugesh-adobe-patch-1--mmsg-oly--aemsites.hlx.live/

metadata path updated

---

paths.json

Test URLs:
- After: https://mrugesh-adobe-patch-1--mmsg-oly--aemsites.hlx.live/

path updated

---

paths.json

Test URLs:
- After: https://mrugesh-adobe-patch-1--mmsg-oly--aemsites.hlx.live/

Mrugesh adobe patch 1

---

component-definition.json
component-filters.json
component-models.json

Adding the initial version of the sample calculator block

---

blocks/calculator/api/getAutoDetailOnMakeModel.js
blocks/calculator/api/getMakes.js
blocks/calculator/api/getModels.js
blocks/calculator/api/getVehicleImageOnNVIC.js
blocks/calculator/calculator.css
blocks/calculator/calculator.js
component-models.json

Updating the sample calculator block

---

blocks/calculator/calculator.css

Updating the styles of sample calculator block

---

blocks/calculator/api/getAutoDetailOnNVIC.js
blocks/calculator/calculator.css
blocks/calculator/calculator.js

Updated the styles for the calculator block

---

blocks/car-card/car-card.css
blocks/wishlist/wishlist.css
blocks/wishlist/wishlist.js

Test URLs:
- After: https://wishlist-component-small--mmsg-oly--aemsites.hlx.live/

Wishlist component small

---

blocks/calculator/api/getAutoDetailOnMakeModel.js
blocks/calculator/api/getAutoDetailOnNVIC.js
blocks/calculator/api/getMakes.js
blocks/calculator/api/getModels.js
blocks/calculator/api/getVehicleImageOnNVIC.js
blocks/calculator/calculator.js

Updating the API key to be read from the authoring site

---

blocks/calculator/calculator.js

Updating the calculator block

---

blocks/columns/columns.css

Test URLs:
- After: https://issue-fixes-NL--mmsg-oly--aemsites.hlx.live/

few fixes from accessbility point of view

---

blocks/cards/cards.css
blocks/columns/columns.css
blocks/form/form.css
styles/styles.css

Test URLs:
- After: https://fixes--mmsg-oly--aemsites.hlx.live/

fixed issues on novated lease page and electric page

---

blocks/accordion/accordion.css
styles/styles.css

Test URLs:
- After: https://accordion-css--mmsg-oly--aemsites.hlx.live/

accordion css added

---

blocks/cards/cards.css

Test URLs:
- After: https://fixes--mmsg-oly--aemsites.hlx.live/

fixed issues for card- article component

---

blocks/cards/cards.css

Reverts aemsites/mmsg-oly#105
Before: https://main--mmsg-oly--aemsites.hlx.page/
After: https://revert-105-fixes--mmsg-oly--aemsites.hlx.page/

Revert "fixed issues for card- article component"

---

blocks/hero/hero.css
component-models.json

Test URLs:
- After: https://bug-homepage--mmsg-oly--aemsites.hlx.live/

Bug homepage

---

.prettierignore
blocks/hero/hero.css
blocks/wishlist/wishlist.css
blocks/wishlist/wishlist.js
component-models.json
scripts/data.js
scripts/utils.js

Test URLs:
- After: https://car-card-recentlyviewed--mmsg-oly--aemsites.hlx.live/

adds recently viewed with hardcoded sample data

---

blocks/car-card/car-card.css
blocks/cards/cards.css
blocks/columns/columns.css

Fixed alignment issues of
car-details card
article component
2 column and 3 column text components of novated lease page and electric page
benefits
more from oly
Test URLs:
- After: https://car-fixes--mmsg-oly--aemsites.hlx.live/

fixed alignment issue of few components

---

blocks/nl-calculator/api/getAutoDetailOnMakeModel.js
blocks/nl-calculator/api/getAutoDetailOnNVIC.js
blocks/nl-calculator/api/getMakes.js
blocks/nl-calculator/api/getModels.js
blocks/nl-calculator/api/getVehicleImageOnNVIC.js
blocks/nl-calculator/nl-calculator.css
blocks/nl-calculator/nl-calculator.js
component-definition.json
component-filters.json
component-models.json

Test URLs:
- After: https://nl-calculator--mmsg-oly--aemsites.hlx.live/

Adding the initial version of the NL-calculator block

---

component-models.json

Test URLs:
- After: https://single-slide-carousel--mmsg-oly--aemsites.hlx.live/

changes for single slide carousel

---

blocks/wishlist/wishlist.css

fixed alignment issue of few components
Test URLs:
- After: https://car-fixes--mmsg-oly--aemsites.hlx.live/

fixed wishlist changes

---

component-definition.json
component-filters.json
component-models.json

Test URLs:
- After: https://takeways--mmsg-oly--aemsites.hlx.live/

adds takeways component

---

blocks/header-nav/header-nav.css
blocks/header-nav/header-nav.js
component-definition.json
component-filters.json
component-models.json

Test URLs:
- After: https://thumbnail-block--mmsg-oly--aemsites.hlx.live/

added thumbnail block

---

helix-query.yaml

Test URLs:
- After: https://car-detail--mmsg-oly--aemsites.hlx.live/

vehicle offers query index updated

---

helix-query.yaml

Test URLs:
- After: https://offer-dynamic--mmsg-oly--aemsites.hlx.live/

helix query udpated

---

component-definition.json
scripts/scripts.js

Test URLs:
- After: https://component-rename--mmsg-oly--aemsites.hlx.live/

component giving them meaning full name

---

blocks/wishlist/wishlist.js

Test URLs:
- After: https://wishlist-js-fix--mmsg-oly--aemsites.hlx.live/

fixes js fix for wishlist

---

blocks/car-card/car-card.css
blocks/car-card/car-card.js
scripts/data.js
styles/styles.css

ss-
Test URLs:
- After: https://car-card-new--mmsg-oly--aemsites.hlx.live/

Changes for adding the oly deals and ev symbol in the car cards

---

blocks/hero/hero.css
blocks/hero/hero.js
blocks/thumbnail-car/thumbnail-car.css
blocks/thumbnail-car/thumbnail-car.js
component-models.json

Test URLs:
- After: https://thumbnail-block--mmsg-oly--aemsites.hlx.live/

added thumnail component block

---

blocks/cards/cards.css
blocks/columns/columns.css
blocks/footer/footer.css

Test URLs:
- After: https://bug-fixes--mmsg-oly--aemsites.hlx.live/

fixed issues of footer, article block and more from oly

---

blocks/thumbnail-car/thumbnail-car.css
blocks/thumbnail-car/thumbnail-car.js
component-models.json

Test URLs:
- After: https://thumbnail-block--mmsg-oly--aemsites.hlx.live/

added ev option

---

blocks/breadcrumb/breadcrumb.css
blocks/header-nav/header-nav.css
component-models.json

Test URLs:
- After: https://bugs-common--mmsg-oly--aemsites.hlx.live/

Fixed bugs

---

helix-query.yaml
paths.json

Test URLs:
- After: https://formpath--mmsg-oly--aemsites.hlx.live/

path are updated for forms

---

scripts/config.js
scripts/delayed.js

Test URLs:
- After: https://231009-global-adobe-launch-codes--mmsg-oly--aemsites.hlx.live/

231009 - global adobe launch scripts addition

---

blocks/columns/columns.css
component-definition.json
styles/styles.css

Test URLs:
- After: https://bug-fixes-1--mmsg-oly--aemsites.hlx.live/

fixed issues from insurance, more from oly

---

component-definition.json
component-models.json

Test URLs:
- After: https://takeaway--mmsg-oly--aemsites.hlx.live/

hotfixes for takeaway

---

component-definition.json
component-models.json

Updating the nl-calculator model for testing

---

.eslintrc.js
component-models.json

Updating the nl-calculator model

---

blocks/accordion/accordion.css
blocks/form/form.css
blocks/thumbnail-car/thumbnail-car.css
styles/styles.css

Test URLs:
- After: https://bugs-common--mmsg-oly--aemsites.hlx.live/

Fixed issues

---

component-definition.json
component-models.json

Test URLs:
- After: https://takeaways-hotfix--mmsg-oly--aemsites.hlx.live/

Takeaways hotfix

---

paths.json

Test URLs:
- After: https://pathupdate1--mmsg-oly--aemsites.hlx.live/

Pathupdate1

---

blocks/nl-calculator/nl-calculator.js

Updating the nl-calculator block to hide the content

---

blocks/car-card/car-card.css
blocks/car-card/car-card.js
blocks/car-card/common-car-utils.js
blocks/wishlist/wishlist.css
blocks/wishlist/wishlist.js

Test URLs:
- After: https://wishlistrefactor--mmsg-oly--aemsites.hlx.live/

Wishlistrefactor

---

component-definition.json
component-models.json

Test URLs:
- After: https://filter--mmsg-oly--aemsites.hlx.live/

filter skeleton

---

component-filters.json

Test URLs:
- After: https://filter--mmsg-oly--aemsites.hlx.live/

adds filter

---

.eslintrc.js
component-models.json

Updating the nl-calculator block model

---

blocks/accordion/accordion.css
blocks/cards/cards.css
blocks/columns/columns.css
blocks/single-slide-carousel/single-slide-carousel.css
styles/styles.css

Test URLs:
- After: https://article-card--mmsg-oly--aemsites.hlx.live/

Issues fixed for novated lease page as per bug -233008

---

blocks/related-article-card/related-article-card.css
component-models.json

Test URLs:
- After: https://hotfix-related-articles--mmsg-oly--aemsites.hlx.live/

WIP on related-articles-hotfix

---

blocks/related-article-card/related-article-card.css

Test URLs:
- After: https://hotfix-related-articles--mmsg-oly--aemsites.hlx.live/

hotfix related article

---

blocks/nl-calculator/nl-calculator.css
blocks/nl-calculator/nl-calculator.js

Disabling the UI view of nl-calculator

---

blocks/form/form.css
blocks/form/form.js
blocks/form/request-callback.js
paths.json

- After: https://google-recaptcha--mmsg-oly--aemsites.hlx.live/

adding space

---

blocks/columns/columns.css

Test URLs:
- After: https://hover-card--mmsg-oly--aemsites.hlx.live/

Add Hover Card CSS

---

component-models.json

Updating the nl-calculator block model with filters

---

blocks/related-article-card/related-article-card.css

Test URLs:
- After: https://hotfix-related-articles--mmsg-oly--aemsites.hlx.live/

WIP on hotfix-related-articles

---

paths.json

- After: https://update-paths--mmsg-oly--aemsites.hlx.live/

changed paths

---

blocks/form/form.css
blocks/form/form.js
blocks/form/request-callback.js
blocks/hero/hero.css

- After: https://google-recaptcha--mmsg-oly--aemsites.hlx.live/

Google recaptcha

---

blocks/form/form.css

- After: https://google-recaptcha--mmsg-oly--aemsites.hlx.live/

added css code

---

helix-query.yaml

Test URLs:
- Before: https://main--mmsg-oly--aemsites.hlx.page/
- After: https://branchu--mmsg-oly--aemsites.hlx.page/

query updated

---

helix-query.yaml

Test URLs:
- After: https://branchu--mmsg-oly--aemsites.hlx.live/

helix query updated

---

paths.json

Test URLs:
- After: https://pathup--mmsg-oly--aemsites.hlx.live/

path updates

---

blocks/imagedesc-col2-inline/imagedesc-col2-inline.css
blocks/single-slide-carousel/single-slide-carousel.css
styles/styles.css

Test URLs:
- After: https://article-card--mmsg-oly--aemsites.hlx.live/

bug fixes related to legal and NL

---

README.md
fstab.yaml

Test URLs:
- After: https://closing-repo--mmsg-oly--aemsites.hlx.live/

clossing repo commit
